"""empty message

Revision ID: 559692c759bd
Revises: a1200d4092ba
Create Date: 2025-04-07 20:08:18.149296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '559692c759bd'
down_revision: Union[str, None] = 'a1200d4092ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('user', 'creat_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('creat_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
