"""empty message

Revision ID: b4afb3e687c0
Revises: 1ebdd93ce9b5
Create Date: 2025-04-15 16:32:18.879011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4afb3e687c0'
down_revision: Union[str, None] = '1ebdd93ce9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('modify_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'modify_at')
    # ### end Alembic commands ###
